### ISSUE TITLE
Robot support megaissue

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildcraftCompat#12]
Harvester
- [x] Apple&Milk&Tea 2
- [x] AgriCraft
- [x] Witchery - anyone willing to look at this?

Planter
- [x] Forestry trees (on their side)

Miner
- [x] GregTech ores (WARNING: highly nontrivial)

Useful comments:
- https://github.com/BuildCraft/BuildCraft/issues/2561

**Comment by hea3ven** [comment]
Any support added to the block searching robots should be handled with care, preferably as WorldProperties, as it will be run in a backround thread. See BuildCraft/BuildCraft#2577

**Comment by asiekierka** [comment]
@hea3ven - I am aware and that's how I'm doing it.

**Comment by Amelia-** [comment]
I'm having problems with my planter robots not picking up and planting Forestry saplings. The robots work fine in the same setup when used with vanila saplings.
This is with Forestry version 3.7.0.636 unstable, BuildcraftCompat 7.0.9 and Buildcraft 7.0.16.

Do I take this up to the Forestry team or is this something in BuildcraftCompat?
