### ISSUE TITLE
Reminder: Move Apiarist Pipe from Forestry to BC Compat

### ISSUE THREAD

**Issue by LouisHutch** [BuildCraft/BuildcraftCompat#17]
See: https://github.com/ForestryMC/ForestryMC/issues/396 and https://github.com/ForestryMC/ForestryMC/pull/687

**Comment by mezz** [comment]
Going to take a stab at this

**Comment by mezz** [comment]
Made some good progress here: https://github.com/mezz/BuildcraftCompat/commit/c9c6c5f2f824046293bfdb9c22200e9fa1f830a8

TODO:
[ ] Move all language's localizations
[ ] Add network handler for BC Compat
