### ISSUE TITLE
Quarry & ThermalDynamics Itemduct w/servo

### ISSUE THREAD

**Issue by Hazmatik** [BuildCraft/BuildcraftCompat#19]
When I attach an Itemduct to a Buildcraft Quarry it works fine, but if I attach a servo onto it (to set it to round robin mode) it just starts shooting items into the air as if there was no duct attached to the quarry. I'm playing on the FTB Infinity pack. This is with Thermal Dynamics version 1.0.0 and BuildCraft version 6.4.14 and BuildCraft Compat version 6.4.2

I posted this on Thermal Dynamics Github and was told this was a BC issue and also that BC Compat had support for this however I still have the issue.

**Comment by asiekierka** [comment]
You should NOT have a servo on a quarry. The quarry injects items into the duct and does not have an internal buffer. If you want to do sorting, do it elsewhere.
