### ISSUE TITLE
Move old 1.6 MFR-BC integration to BC Compat

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraftCompat#21]
The integration was originally part of MFR but was removed in the porting of MFR to 1.7. This integration involved things such as the Oil Fabricator etc.

I doubt this will be done any time soon but is here as a reminder if anyone wants add it.

**Comment by asiekierka** [comment]
Adding blocks such as the Oil Fabricator is outside of BC Compat's area. Most of the remaining integration stuff (for actual compatibility) should already be in.
