### ISSUE TITLE
BuildCraft Compat 7.0.5 crashes if BC Transport is not installed

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [BuildCraft/BuildcraftCompat#22]
Game crashes after starting if i try to load it without BC Transport installed.
If i remove BCC or add BC Transport, game loads fine.
On BC 7.0.5 RC and BCC 7.0.3 everything works well.
Crash log - http://pastebin.com/uVr5jbyN

**Comment by YuRaNnNzZZ** [comment]
Tried BC 7.0.7 and BCC 7.0.6, still crashing.
http://pastebin.com/xzHFjhF0

**Comment by asiekierka** [comment]
Why'd you close this? It's very clearly our fault.

For now, play without BCC; I'd love to do a new release today but, admittedly, BCC is not a necessity and I need some time to review BCC in this aspect.
