### ISSUE TITLE
[7.0.5] Crash when right clicking apiarist pipe

### ISSUE THREAD

**Issue by stevenlr** [BuildCraft/BuildcraftCompat#23]
Buildcraft 7.0.6
Buildcraft compat 7.0.5
Forestry3.5.7.16
Forge 10.13.3.403

Right-clicking an apiarist pipe crashes the game.

Crash report : http://pastebin.com/HMy2TJDX

**Comment by mezz** [comment]
Confirmed, working on a fix (not a difficult fix)
