### ISSUE TITLE
BC Builder: Forge Microblock Rotation

### ISSUE THREAD

**Issue by SamuelFoster** [BuildCraft/BuildcraftCompat#29]
(I'm not sure if this is the correct place to post this.)

It looks like the builder doesn't "properly" rotate forge microblocks.

In the screenshot below, an architect table (left) records the positions of some microblock strips, and a builder (right) places them at a 90 degree rotation.

![2015-06-26_18 53 00](https://cloud.githubusercontent.com/assets/5395381/8389997/4d6fc0b8-1c35-11e5-863a-137d3e0302d5.png)

**Comment by loordgek** [comment]
@Chicken-Bones builder fmp support is not working

**Comment by Chicken-Bones** [comment]
@asiekierka Any log info for this?

**Comment by asiekierka** [comment]
I don't have any with me right now as I'm on vacation. ForgeCraft
reproduces it reliably, AFAIK.

**Comment by MikrySoft** [comment]
@Chicken-Bones #32 is somewhat related - microparts don't work AT all, logs provided there.

**Comment by asiekierka** [comment]
@Chicken-Bones - just as a note: I'm delaying release of BCCompat 7.0.9 until this is fixed... this has been a bug for a while but nobody made me aware of it

**Comment by Chicken-Bones** [comment]
Aah, the information that downgrading FMP fixes it is very useful, and makes sense. I'd forgotten about that

**Comment by Chicken-Bones** [comment]
#35
