### ISSUE TITLE
BCCompat shouldn't create a fake world for testing tiles

### ISSUE THREAD

**Issue by liach** [BuildCraft/BuildcraftCompat#33]
https://github.com/CovertJaguar/Railcraft/issues/653

Somewhat when BuildCraftCompat tries to create a TileEntity in a fake world in post init phase, it causes a crash (actually it's such a bad idea to instantiate a world and a tile when it is not available). Here I state that asiekierka should use another way in order to determine whether that tile is immibis' tile and, maybe by using some ugly hack, instead of causing some break.

**Comment by asiekierka** [comment]
There is no other way to get a TileEntity from a Block.
