### ISSUE TITLE
Kinesis pipe wont connect to some MFR machines

### ISSUE THREAD

**Issue by Casper-O** [BuildCraft/BuildcraftCompat#37]
Some MFR machines wont connect to BC MFR machines when BuildcraftCompat is installed i added some screenshots of the issue over at MFR

skyboy/MineFactoryReloaded/issues/474

From an other issue over at Buildcraft repo some found out it worked if buildcraftCompat was removed and @Inari-Whitebear have spoke with @skyboy that says BuildcraftCompat breaks the default connection override to RF-providers

https://github.com/BuildCraft/BuildCraft/issues/2861#issuecomment-126840260

**Comment by asiekierka** [comment]
Fixed in 7.0.10.
