### ISSUE TITLE
Builder able to turn Forestry normal wood variant into the Forestry Fireproof wood variant

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildcraftCompat#38]
BC 7.0.20
BCC 7.0.11
Forestry 1.7.10-3.6.3.20

If you have a Blueprint which contains Forestry Fireproof wood, and if you place the normal variant of that wood in the builder in a slot before the fireproof wood. Tthe builder will take the normal wood and will place down fireproof wood and not use up the fireproof wood which was in the builder.

**Comment by knexer** [comment]
I can reproduce this.

The builder refuses to place anything if only the regular wood is present in the inventory; once the fireproof wood is present, it places the first Forestry wood it can find (fireproof or not, even with different metadata)

**Comment by knexer** [comment]
BuildcraftCompat doesn't seem to have any specific support for Forestry wood.  Confirmed by removing BuildcraftCompat Forestry support locally and reproducing the issue.  I believe this is a Buildcraft issue.

**Comment by LuigiHutch** [comment]
Well, I told Asie on IRC and he said it was a BC Compat issue so I put it here :)

**Comment by AEnterprise** [comment]
any bugs with the builder building stuff from other mods is a BCC issue, no support for other mods will be added in BC, only in BCC
