### ISSUE TITLE
Please Fix the support MineTweaker3

### ISSUE THREAD

**Issue by Tsyklop** [BuildCraft/BuildcraftCompat#41]
https://github.com/stanhebben/MineTweaker3/issues/221#issuecomment-133822243

**Comment by Tsyklop** [comment]
https://github.com/stanhebben/MineTweaker3/issues/264

**Comment by asiekierka** [comment]
Because we still haven't gotten around to it.

With the new Integration Table design, adding a sufficiently good Integration Table support for MT3 is nearly impossible, I'm afraid.

**Comment by Tsyklop** [comment]
@asiekierka A problem with the Refinery fix?
