### ISSUE TITLE
JSON API for Builders Compat

### ISSUE THREAD

**Issue by Kubuxu** [BuildCraft/BuildcraftCompat#44]
Today I wanted to add BC Compat with ZettaIndustries and I discovered that all block in it require only simple NBT white or blacklisting.

It would be beneficial for BC to have some easier API for Builders like some form of JSON API.

It could be a centralized in BCCompat repo but if mods could include it in their jars and didn't have to reference BC directly, nor use any of its classes, it would be even better.

I was thinking about something along those lines:

``` json
{
  "zettaindustries": [
    "quarryfixer",
    "variableredstoneemitter",
    {
      "name": "rfmeterblock",
      "tagBlacklist": ["value", "lastValue"],
      "roatation": "4WayMeta"
    },
    "nfcreader",
    "nfcprogrammer",
    "ecatalogue"
  ]
}
```

It would probably increase popularity of making at least some blocks compatible with BC by mod authors.

EDIT: Rotation could be done by creating some default rotation methods like: `4WayMeta`, `6WayMeta` (based on ForgeDirection) and allowing rotation matrices and NBT based matrices like

``` json
"rotation": {
  "tag": "rot",
  "type": "byte",
  "matrix": [4,7,9,3]
}
```

where `matrix` tells you how to transform from value `X` to clockwise rotation.

**Comment by loordgek** [comment]
https://github.com/BuildCraft/BuildCraft/commit/0a1b5569d5389b38d1c613825af9e5f1ce092bcc
