### ISSUE TITLE
Add OreDict support to MineTweaker Assembly Table handler

### ISSUE THREAD

**Issue by ghost** [BuildCraft/BuildcraftCompat#45]
I'm trying to use more than one of an item in an Assembly Table recipe, but if I use the expression [ore:ingredient \* 2] in the recipe I get the error "Not a valid assembly table ingredient" [full error here](http://pastebin.com/RerxWrVt)

**Comment by asiekierka** [comment]
I am afraid our current Assembly Table code does not support the Ore Dictionary.
