### ISSUE TITLE
Builder having trouble with forge multipart again

### ISSUE THREAD

**Issue by BBoldt** [BuildCraft/BuildcraftCompat#46]
This time the blocks get used up but don't actually get placed in the world.
https://dl.dropboxusercontent.com/u/134976541/ShareX/2015-10/2015-10-18_16-30-32.mp4
- ForgeMultipart-1.7.10-1.2.0.345-universal
- buildcraft-7.1.11
- buildcraft-compat-7.1.2
- forge-1.7.10-10.13.4.1492-1.7.10-universal

**Comment by BBoldt** [comment]
Another example if it helps: https://youtu.be/W-hrDhwhufo?t=1105

**Comment by YuRaNnNzZZ** [comment]
The problem must likely related to [this commit](https://github.com/BuildCraft/BuildCraft/commit/4e38f7e0278df614f4be8098e048da4fed60fb5c), as builder prints this in the log after placing multipart:
```
Placed block does not match expectations! Most likely a bug in BuildCraft or a supported mod. Removed mismatched block.
Location: 89, 58, 566 - Block: ForgeMultipart:block@0
```

**Comment by asiekierka** [comment]
The fix is too easy. I can't believe I haven't done this two years ago.

I'm sorry.

**Comment by AEnterprise** [comment]
You know what they say: better late then never 😃
