### ISSUE TITLE
Waterhook compatability

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildcraftCompat#47]
Waterhook is a mod which adds an event to Forge that is fired when Minecraft creates a water source block (infinite water). http://minecraft.curseforge.com/projects/waterhook

This I believe will allows you to cancel water creating infinite water sources. This could be added to allow the Pump to remove water in the pool below it is bigger than a 3x3 if waterhooks is installed (just and idea).

EnderIO Addons (http://minecraft.curseforge.com/projects/ender-io-addons) is an example of a mod that has Waterhook compat and it will allow the Drain to remove water from the world. Otherwise the infinite water pools will remain.

**Comment by LuigiHutch** [comment]
BC compat for 1.7.10 is EOL so this issue can be closed. If I am reading this correctly, this can be done without the waterhook mod as of Forge 1.10.2-12.18.1.202+ with the merging of this commit https://github.com/MinecraftForge/MinecraftForge/pull/3110

**Comment by AEnterprise** [comment]
that event will indeed allow for that but the pump atm won't respect that, might be worth looking into BC firing that event when pumping from said 3x3 pump and see if a new source would apear, if so it wouldn't remove it but if the event doesn't allow it it should remove it. This means some ticktime firing the event but that will still be significantly less then spamming block and lighting updates

**Comment by LuigiHutch** [comment]
Yup, as this is now a BC issue, I will open an issue on the main BC repo nearer/after the 1.9.X/1.10.X port to avoid distractions :)

**Comment by AlexIIL** [comment]
You've already distracted me with a notification :P

Just open it now, I am already planning on dropping 1.9.x support for BC anyway, so it won't make much difference other than adding an event.
