### ISSUE TITLE
[Crash]: BC Compat Crash with EnderStorage and No Builders Module

### ISSUE THREAD

**Issue by Lanse505** [BuildCraft/BuildcraftCompat#48]
BC Compat Crash:
http://pastebin.com/hkDNpLLy

Mod List: 
http://puu.sh/kVg5E/785c757d85.png

FYI This is a Completely Alpha Private Pack.

P.s this is using; 
BC Compat 7.1.2
BC Modules - V.7.1.12:
Core, 
Energy, 
Factory, 
Silicon, 
Transport

**Comment by AEnterprise** [comment]
for reference: https://github.com/BuildCraft/BuildCraft/issues/3096

**Comment by asiekierka** [comment]
Yup, that is a bug. For now, disable the EnderStorage module.

Dnia 25 paź 2015 o godz. 19:02 Lanse505 notifications@github.com napisał(a):

**Comment by Lanse505** [comment]
Okey ^^

**Comment by AEnterprise** [comment]
@Lanse505 no need to close this issue, your crash is gone by dissabeling the module but the bug remains
