### ISSUE TITLE
Facades recipes config

### ISSUE THREAD

**Issue by Usernm0** [BuildCraft/BuildcraftCompat#53]
Please, make config option to not show in NEI all facade recipes on assembly table.

**Comment by AEnterprise** [comment]
if you don't want to see the facades in nei you could open the subsets menu and dissable the facades creative tab

**Comment by LuigiHutch** [comment]
There already is one added in 7.1.13 :p

**Comment by Usernm0** [comment]
I talk about assembly recipes, that you can see if press U (usage) on near every block. NEI subsets not solve problem with it, and i don't know any other tools like minetweaker to hide(not remove) this recipes.

**Comment by AEnterprise** [comment]
how is that a problem? you can just cycle past the assembly table recipes with one click of a button

**Comment by Usernm0** [comment]
Yes, I do it now. But I try to remove NEI clutter for my mod pack, and feature to hide facade recipes will be useful to me.

**Comment by asiekierka** [comment]
Got bored in a train with no Internet. Expect a release with this requested feature later today.

**Comment by labpaw** [comment]
@asiekierka also, don't forget to merge or decline my PR :)

**Comment by asiekierka** [comment]
Closed via https://github.com/BuildCraft/BuildcraftCompat/commit/fda803fd4efb0b8533dd0fc85fbe0aaf8d251ad1
