### ISSUE TITLE
Logistics Pipes and BuildcraftCompat comaptible

### ISSUE THREAD

**Issue by darkbumerang** [BuildCraft/BuildcraftCompat#56]
Logistics Pipes 0.9.3.70, BC Compat 7.1.13 and BC 7.1.14, minecraft 1.7.10.
Crash Error in uploaded file
http://pastebin.com/vnhupnML
what to do?
Without BCCompat mod, game starts normally with plug logistics pipes
ps.logistics pipes are not connected to the pipes of buildcraft...

**Comment by asiekierka** [comment]
Not a BuildCraftCompat issue.
