### ISSUE TITLE
NEI crash (Integration Table)

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildcraftCompat#58]
See https://github.com/BuildCraft/BuildCraft/issues/3170

**Comment by cosmicdan** [comment]
This is an old one....

This stems from the Gate Expansion recipes being added to the list even when the gate expansion is incompatible with that particular gate (i.e. BC returns null on recipe output). I did a temp fix on my local clone by adding a couple null-checks to RecipeHandlerIntegrationTable, but it still returns a "blank output" on NEI's usage screen for these gate + expansion combinations. I'm a bit lost on that, and I don't really want to spend any more novice time on this.

Any ideas?

**Comment by cosmicdan** [comment]
This is an old one....

This stems from the Gate Expansion recipes being added to the list even when the gate expansion is incompatible with that particular gate (i.e. BC returns null on recipe output). I did a temp fix on my local clone by adding a couple null-checks to RecipeHandlerIntegrationTable, but it still returns a "blank output" on NEI's usage screen for these gate + expansion combinations. I'm a bit lost on that, and I don't really want to spend any more time on this (I'm only a novice).

Any ideas?

EDIT: Here is my dodgy fix:

```
@@ -103,10 +103,12 @@ public class RecipeHandlerIntegrationTable extends RecipeHandlerBase
             }
             if (!found) {
                 continue;
             }
             crecipe.setIngredientPermutation((Collection)crecipe.inputs, ingredient);
+            if (crecipe.getResult() == null)
+               continue;
             this.arecipes.add(crecipe);
         }
     }

     public class CachedIntegrationTableRecipe extends CachedBaseRecipe {
@@ -155,11 +157,15 @@ public class RecipeHandlerIntegrationTable extends RecipeHandlerBase
             ItemStack input = ingr.get(0).item;
             List<ItemStack> exps = new ArrayList<ItemStack>();
             for (int i = 1; i < ingr.size(); i++) {
                 exps.add(ingr.get(i).item);
             }
-            return new PositionedStack(recipe.craft(input, exps, true), 138 - 5, 49 - 13, true);
+            
+            ItemStack expansionResult = recipe.craft(input, exps, true);
+            if (expansionResult != null)
+               return new PositionedStack(expansionResult, 138 - 5, 49 - 13, true);
+            return null;
         }

         public List<PositionedStack> getIngredients() {
             return (List<PositionedStack>)this.getCycledIngredients(cycleticks / 20, (List)this.inputs);
         }


```

**Comment by AEnterprise** [comment]
as 1.7.10 is EOL and NEI doesn't exist in 1.8+ this will probably never be fixed, JEI recipe handlers are completely different and alot of BC is being rewritten so for the JEI integration it's probably no problem

so this will probably never be fixed on 1.7.10

**Comment by cosmicdan** [comment]
Ah yeah that's right, fair enough. RIP NEI!

**Comment by AEnterprise** [comment]
indeed, the time needed to fix this is better spent on other things as it requires rewriting that handler and maybe how recipes are returned

**Comment by asiekierka** [comment]
1.7.10 is not entirely EOL - valid fixes will still be pushed and released for as long as 1.7.10 is in popular use (or BuildCraft 8.0.0 comes out, whichever comes first).

**Comment by AEnterprise** [comment]
with EOL i mean it's not the branch that is actively worked on and as far as i know only critical bugfixes are being done to it unless the bug also exists on the newer versions and isn't to much of a pain to do on both sides

**Comment by asiekierka** [comment]
The specifics are closer to "AlexIIL generally develops the new codebase, I
have retired from BuildCraft but remain the de-facto 'maintainer' of 1.7.10
and I will integrate patches if they appear".

2016-07-14 10:24 GMT+02:00 AEnterprise notifications@github.com:
