### ISSUE TITLE
[7.1.x] P:Red bundled cable compatibility NPE

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildcraftCompat#59]
https://github.com/BuildCraft/BuildCraft/issues/3265

**Comment by AlexIIL** [comment]
Crash report file (for reference): https://pastebin.com/qya93x2i

**Comment by AlexIIL** [comment]
It looks like this mistakenly assumes that "ProjRed|Core" provides ````ProjectRedAPI.transmissionAPI````, when it is instead "ProjRed|Transmission" (A separate mod).

**Comment by AlexIIL** [comment]
@lelodragneel, can you try installing "Project Red: Integration" and trying again?
