### ISSUE TITLE
Integration table recipes not working properly

### ISSUE THREAD

**Issue by Nentify** [BuildCraft/BuildcraftCompat#6]
The integration table's recipes shows 4 recipes all looking like this across two pages. Pressing R on most of the gates will also show you these 4 recipes with the basic gate (red wire) as the output and varying RF requirements. Clicking the 'recipes' button (oddly placed, you have to click next to the arrow also shows the robot recipe on page 3.

Mod versions:
- Minecraft Forge 10.13.2.1291
- Buildcraft 6.3.3, 6.3.6 (tested both)
- Buildcraft Compat 6.3.1
- NEI Integration 1.0.5, 1.0.6
- NotEnoughItems 1.0.4.83

Screenshots:
![](http://i.nentify.me/QODdk2nZ.png)
![](http://i.nentify.me/6WhIRB7M.png)

**Comment by Zarkov2** [comment]
I'm seeing the same behavior, using:
* Minecraft Forge 10.13.2.1291
* BuildCraft 6.4.2
* BuildCraft Compat 6.4
* NEI 1.0.4.90
* NEI Integration 1.0.7

**Comment by Kubuxu** [comment]
Problem is that integration recipes are dynamic so it is not possible to deduce output to input mapping. Special handlers have to be introduced.

**Comment by asiekierka** [comment]
Fixed-ish somewhat-ish. Can't really do much more.
