### ISSUE TITLE
BC and Ex Nihilo compatibility.

### ISSUE THREAD

**Issue by KyonV2** [BuildCraft/BuildcraftCompat#72]
I'm trying to get Leaf Cutter robot to cut Infested leaves from Ex Nihilo, no luck so far using crook or shears. Would it be possible to make it work somehow? 

Thanks

**Comment by AlexIIL** [comment]
What versions of the mods (BC and Ex Nihilo) are you using?

**Comment by KyonV2** [comment]
I'm playing the newest PO2 on 1.7.10
buildcraft-7.1.18
buildcraft-compat-7.1.5
Ex-Astris-Rebirth-MC1.7.10-1.01-45
Ex-Nihilo-1.38-53

**Comment by AlexIIL** [comment]
I don't have an environment with Ex Nihilo atm, but the way the leaf cutter robot works is by checking to see if the block's item has been registered with the oredictionary as "treeLeaves". I'm not sure if Ex Nihilo registers the leaves as that, but can you try adding it to craft tweaker to test?

**Comment by KyonV2** [comment]
asiekierka helped me on reddit. Gave me this:
val ore = <ore:treeLeaves>;
ore.add(<exnihilo:infested_leaves>);

Leaf cutter now cuts them but only when these are <100% infested. After they turn 100% he doesn't recognize them. 

http://qs.lc/3yr7b

I guess it just turns to other block after 100%, a block which I can't spawn nor find in NEI.

I will add that I'm complete noob in this kind of stuff so just FYI.

**Comment by asiekierka** [comment]
Infested Leaves have additional drops which are only done in removedByPlayer. That, coupled with them not being part of treeLeaves, makes me assume that they are not supposed to be automatable.

If a person of sufficient authority declares otherwise, this may be revisited, but for now I do not think an official fix will come.
