### ISSUE TITLE
Oredictionary issue on server join?

### ISSUE THREAD

**Issue by InjuredWolf** [BuildCraft/BuildcraftCompat#80]
When trying to join a server, it doesn't let me join, giving me this error: 
![image](https://user-images.githubusercontent.com/10350531/36364091-1aee307c-1596-11e8-9f65-2c307009fc1f.png)

Buildcraft 7.99.15
BuildcraftCompat 7.99.14
Forestry 5.8.0.250
Forge build 2618
MC 1.12.2

**Comment by MartinEggerstedt** [comment]
I have the same problem with the same versions.
Server is starting fine but client can't connenct

**Comment by AEnterprise** [comment]
are there other mods involved or is there a mismatch between client and server? this works fine on the test server

**Comment by MartinEggerstedt** [comment]
It is an Direwolf20 1.12.2 Server. i added buildcraft to it and just updated to version 1.9.0 from the pack.
And updated the Buildcraft versions from 7.99.14 und compat 7.99.13 to 7.99.15 and compat 7.99.14.
The strange thing is that when i start a Singleplayerworld with the Client ist works.
i downgraded buildcraft and compat on server and client and i can join the server now.
For testing i started a new server world with the newer versions of buildcraft and compat. Then i get the error again. 
This ist what i found in the client log:
[13:55:39] [Netty Client IO #1/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.RegistryEvent$MissingMappings@36a4dcf6:
java.lang.IllegalStateException: The object net.minecraftforge.oredict.ShapedOreRecipe@68fae84b (name buildcraftcompat:pipe_item_propolis_colorless) is being added too late.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:316) ~[ForgeRegistry.class:?]
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:275) ~[ForgeRegistry.class:?]
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:108) ~[ForgeRegistry.class:?]
	at buildcraft.compat.module.forestry.pipe.ForestryPipes.addPipeRecipe(ForestryPipes.java:76) ~[ForestryPipes.class:?]
	at buildcraft.compat.module.forestry.pipe.ForestryPipes.registerRecipes(ForestryPipes.java:59) ~[ForestryPipes.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_658_ForestryPipes_registerRecipes_RegistryEvent.invoke(.dynamic) ~[?:?]

**Comment by MartinEggerstedt** [comment]
Hi,
just updated the Server to Direwolf-Pack to 1.10. 
Same World. Problem is gone now.

**Comment by ipatix** [comment]
I'm doing a bit of modpack creation and playing stuff with my friend and I'm facing exactly the same problem.
@MartinEggerstedt mentioned it was fixed for him by updating Direwolf, but we can't do that. Is there anything specific we can do to work around that problem?

It would be helpful to get some insight if it's "our" fault or there actually is a problem with BCC.

**Comment by AlexIIL** [comment]
I'm not sure what could be causing it, as it doesn't happen in dev or in a server (with just buildcraft or BCC) so I assume there's another mod helping to cause this.

**Comment by ipatix** [comment]
Is there anything I could do to try to debug this?

**Comment by AEnterprise** [comment]
try a binary mod search maybe? that should uncover the 3rd mod involved

**Comment by ipatix** [comment]
So, my friend just told me that this seems to be caused by a combination of BC and CraftTweaker.

This is an example script for CraftTweaker that seems to cause this problem:
[ThermalExpansion.zip](https://github.com/BuildCraft/BuildCraftCompat/files/1876921/ThermalExpansion.zip)

**Comment by AEnterprise** [comment]
i guess crafttweaker must be doing something with it's recipe manipulation that is somehow locking down the registry prematurely

**Comment by MartinEggerstedt** [comment]
Hi all,
the problem is back for me.
Don't know why. I can still start a Single Player World with the Client, but can't join the Server without deactivating the forestry module.

I have a question about the Apiarist Pipe. 
When i check the Pipe on a Singleplayerworld with /ct hand  ist shows me: <buildcraftcompat:pipe_item_propolis>
The Error when joining the server said that there is a problem with <buildcraftcompat:pipe_item_propolis_colorless>
But there is only one Apiarist Pipe. I startet a World with just Buildcraft, Compat, Forestry and JEI.
It show's only one Pipe there. 

So what is the colorless Variant ? Is that something that is not implemented full at the moment ?

**Comment by AlexIIL** [comment]
@MartinEggerstedt This is an issue with pipe *recipes*, not the items themselves. Pipes currently add 17 recipes, one is the colourless variant (added first) and then the 16 for each colour.

**Comment by MartinEggerstedt** [comment]
yes that's what i mean (sorry english is not the best)
There ist only one Variant showing in Minecraft. No recipes for crafting the colored ones.
neither are they showing up in jei or creative mode

**Comment by AlexIIL** [comment]
Do recipes for the other buildcraft pipes show in JEI?

(In creative mode we only show the uncoloured ones, as otherwise it would show a silly amount of them)

**Comment by MartinEggerstedt** [comment]
ok sorry didn't know that you can paint the pipes.
Tested with the aparist pipe and paint it orange, break it and get the orange apiarist pipe.
so i was on the wrong path.

**Comment by BaseCrusher** [comment]
Got the same issue. 
Turning off the Forestry module of Buildcraft let you join the server without any errors.
If i remeber it correctly the propolist was used to craft the apiarist pipe. But Forestry has his own king of apiarist pipe now, wich support, but doesn't need buildcraft to be insalled. 
It might have something to do with that.

**Comment by sintaxcz** [comment]
Hello guys nice that issue has been fixed but in BuildcraftCompat 7.99.14 is still present i try to compile but i dont have all dependencies can you please make new build with this fix ?

**Comment by AlexIIL** [comment]
Woops, looks like I never actually released compat 7.99.15 properly...

Thanks for reminding me! It should be out within the next few days.

**Comment by kerams** [comment]
Polite bump :)

**Comment by AlexIIL** [comment]
Ok, *actually* released now: https://www.mod-buildcraft.com/buildcraftcompat-79915.html. Thanks for reminding me!
