### ISSUE TITLE
1.7.10 - Builder cannot correctly handle collapsible block

### ISSUE THREAD

**Issue by harvald** [BuildCraft/BuildcraftCompat#82]
I've build something like that
![2018-05-29_21 58 28](https://user-images.githubusercontent.com/3062058/40682481-26d97132-638c-11e8-86c5-6efee3e1e5a5.png)

After creating blueprint and cloning it with builder i have
![2018-05-29_21 58 50](https://user-images.githubusercontent.com/3062058/40682525-45c56448-638c-11e8-9a30-de0e41b3b227.png)

I have suspicion that rotation could be responsible.

**Comment by asiekierka** [comment]
Carpenter's Blocks 3.3.7 made a breaking change to the way Collapsible Blocks are stored.

**Comment by asiekierka** [comment]
Fixed in 7.1.8.
