### ISSUE TITLE
Buildcraft Compat not loading in

### ISSUE THREAD

**Issue by BigCasper** [BuildCraft/BuildcraftCompat#84]
I've added Buildcraft Compat for 1.11.2 but it didn't load into Minecraft - no items from it where in NEI or creative eq. I don't know what happend.
Edit: checked that versions are correct.

**Comment by loordgek** [comment]
post logs
witch out them we cant help you

**Comment by BigCasper** [comment]
Which logs?

**Comment by Generalcamo** [comment]
Forge Modloader Logs

**Comment by BigCasper** [comment]
[latest.log](https://github.com/BuildCraft/BuildCraftCompat/files/2147088/latest.log)
Here ya go!
Hope it helps.

**Comment by Generalcamo** [comment]
It's definitely loading it.

What item are you looking for?

**Comment by liach** [comment]
BuildCraft compat does not add items or blocks. It adds intermod support and now it only supports very few mods. One of the supports is JEI recipe displays.

**Comment by BigCasper** [comment]
I got that mod to go with Forestry to have Apiarist's Pipe.
I see the added JEI Assembly Table recipes.

**Comment by BigCasper** [comment]
So what happened to the Apiarist's Pipe then?

**Comment by AlexIIL** [comment]
Nothing - it was added to BC Compat in 7.99.14. Although you do need forestry 5.7.0.236 or later.

**Comment by BigCasper** [comment]
So there are no mods that add Apiarist's Pipe for 1.11?

**Comment by AlexIIL** [comment]
Oh right sorry, I didn't see that you are using 1.11.2.

And no, if we don't add it then it's very unlikely that someone else does.
