### ISSUE TITLE
I need example

### ISSUE THREAD

**Issue by MitiskoSVK** [BuildCraft/BuildcraftCompat#93]
Hi I use buildcraft-compat-7.99.24.5 and i need remove recipe from .AssemblyTable all chipset...
Old version funcional code is:
mods.buildcraft.AssemblyTable.removeByName(<BuildCraft|Silicon:redstoneChipset:*>);
Please give me example new funcional code...

Very thanks

**Comment by AlexIIL** [comment]
Does https://github.com/BuildCraft/BuildCraftCompat/wiki/CraftTweaker-Support-(1.12---7.99.23-and-later) help?

**Comment by AlexIIL** [comment]
Or do you need the recipe IDs?

**Comment by AlexIIL** [comment]
Okay, I've added the recipe ID's to that wiki page - is that enough?

**Comment by MitiskoSVK** [comment]
Thanks you very much, but I have question As I find recipe name ?

**Comment by MitiskoSVK** [comment]
I have still problem...
If I use code: 
//Chipset
mods.buildcraft.AssemblyTable.removeByName(buildcraftsilicon:redstone_chipset);
ERROR: crafttweaker SIDE_CLIENT: Error parsing BuildCraft.zs:16 --) expected
I don´t know what i do wrong...

**Comment by AlexIIL** [comment]
Oh, sorry - you need to put the recipe ID in quotes, like this:
````
mods.buildcraft.AssemblyTable.removeByName("buildcraftsilicon:redstone_chipset");
````

**Comment by MitiskoSVK** [comment]
Wualaaa very nice,  this recipe works... 
Very very thanks...
mods.buildcraft.AssemblyTable.removeByName("buildcraftsilicon:redstone_chipset");
